version: "3.8"

services:

  service-db:
    container_name: service-db
    build: .docker/db
    ports:
      - "50001:3306"
    environment:
      MYSQL_DATABASE: service
      MYSQL_ROOT_PASSWORD: example

  service-db-test:
    container_name: service-db-test
    build: .docker/db
    environment:
      MYSQL_ROOT_PASSWORD: top_secret_test_password
      MYSQL_DATABASE: service-test
      MYSQL_USER: service-user
      MYSQL_PASSWORD: user_secret_test_password
    volumes:
      - type: tmpfs
        target: /var/lib/mysql

  service-fpm:
    container_name: service-fpm
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      target: dev
    environment:
      PHP_IDE_CONFIG: serverName=service.template

      APP_ENV: dev
      APP_SECRET: bdc6c3bd25b539b62994d825de84875e

      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
      DATABASE_NAME: service

      DOCTRINE_DEV_MODE: "true"
      PATH: "/home/user/bin:/var/local/src/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - service-db
    volumes:
      - ./:/var/local/src:delegated
    stdin_open: true
    tty: true

  service-web:
    container_name: service-web
    build: .docker/web
    depends_on:
      - service-fpm
    volumes:
      - ./:/var/local/src:delegated
    ports:
      - "50000:80"