name: Tests

on:
  pull_request:

jobs:

  build-fpm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build PHP Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/php/Dockerfile
          build-args: |
            UID=1001
            GID=116
          tags: we-do-code-ltd/service:fpm
          outputs: type=docker,dest=/tmp/service-fpm.tar
      -
        name: Upload PHP artifact
        uses: actions/upload-artifact@v2
        with:
          name: service-fpm
          path: /tmp/service-fpm.tar

  php-stan:
    needs: build-fpm
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: service-fpm
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/service-fpm.tar
      -
        name: PHP Stan check src directory
        run: |
          docker run we-do-code-ltd/service:fpm \
            vendor/bin/phpstan analyse \
              --level=max \
              --configuration=phpstan-src.neon \
              src \
            && echo "No issues detected!"
      -
        name: PHP Stan check tests directory
        run: |
          docker run we-do-code-ltd/service:fpm \
            vendor/bin/phpstan analyse \
              --level=max \
              --configuration=phpstan-tests.neon \
              tests \
            && echo "No issues detected!"

  coding-standards:
    needs: build-fpm
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: service-fpm
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/service-fpm.tar
      -
        name: PHP CS
        run: |
          docker run we-do-code-ltd/service:fpm \
            vendor/bin/phpcs src tests \
          && echo "No issues detected!"
          
  composer-validate:
    needs: build-fpm
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: service-fpm
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/service-fpm.tar
      -
        name: Composer Validate
        run: |
          docker run we-do-code-ltd/service:fpm \
            /var/local/bin/composer validate --strict

